services:
  gitlab_local:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab_local
    restart: unless-stopped
    # hostname: 'gitlab.localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://host.docker.internal:8888'
        # gitlab_rails['gitlab_host'] = 'gitlab_local'  # Для внутреннего использования
        # gitlab_rails['gitlab_shell_git_url'] = 'http://gitlab_local:80'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['initial_root_password'] = "42314231"
        
        nginx['enable'] = true
        nginx['listen_port'] = 80
        nginx['listen_addresses'] = ['0.0.0.0']
        
        puma['worker_processes'] = 2
        sidekiq['max_concurrency'] = 5
        postgresql['shared_buffers'] = "128MB"
        
        prometheus['enable'] = false
        alertmanager['enable'] = false
    ports:
      - "8888:80"    # Основной веб-порт
      - "2222:22"     # SSH
    volumes:
      - C:/Docker volumes/gitlab/config:/etc/gitlab
      - C:/Docker volumes/gitlab/data:/var/opt/gitlab
      - C:/Docker volumes/gitlab/logs:/var/log/gitlab
    networks:
      - gitlab_local_network
        
  gitlab_runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab_runner
    restart: unless-stopped
    volumes:
      - ./config:/etc/gitlab-runner  # Конфиги
      - /var/run/docker.sock:/var/run/docker.sock  # Для Docker executor
    depends_on:
      - gitlab_local
    networks:
      - gitlab_local_network

networks:
  gitlab_local_network:
    driver: bridge