services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-local
    restart: unless-stopped
    hostname: 'gitlab.localhost'  # Изменил с localhost
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost:8888'  # Соответствует порту
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['initial_root_password'] = "42314231"
        
        # Включим nginx обратно (обязательно для работы)
        nginx['enable'] = true
        nginx['listen_port'] = 80
        nginx['listen_addresses'] = ['0.0.0.0']
        
        # Оптимизации (можно оставить)
        puma['worker_processes'] = 2
        sidekiq['max_concurrency'] = 5
        postgresql['shared_buffers'] = "128MB"
        
        # Можно оставить отключенными
        prometheus['enable'] = false
        alertmanager['enable'] = false
    ports:
      - "8888:80"    # Основной веб-порт
      - "2222:22"     # SSH
      # HTTPS можно добавить позже
    volumes:
      - C:/Docker volumes/gitlab/config:/etc/gitlab
      - C:/Docker volumes/gitlab/data:/var/opt/gitlab
      - C:/Docker volumes/gitlab/logs:/var/log/gitlab
    networks:
      - gitlab-net
    # Добавим для надежности
    extra_hosts:
      - "gitlab.localhost:127.0.0.1"

networks:
  gitlab-net:
    driver: bridge